version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blogdb
    ports:
      - 27017:27017
    volumes:
      - ./blog-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./blog-backend/mongo_data:/data/db
  backend:
    image: blog-backend
    build: 
      context: ./blog-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/blogdb
      - SECRET=<Add your secret here>
    depends_on:
      - mongo
  frontend:
    image: blog-frontend
    build:
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080/api/
      context: ./blog-front
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    ports:
      - 3000:3000
    container_name: frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy